/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurantmanagement.userInterface;

import java.awt.CardLayout;
import javax.swing.JPanel;
import restaurantmanagement.data.JDBCConnection;
import restaurantmanagement.main.MenuDirectory;
import restaurantmanagement.main.TableDirectory;

/**
 *
 * @author kunaltibe
 */
public class UserJPanel extends javax.swing.JPanel {
     JPanel workArea;
     MenuDirectory menuDirectory;
     TableDirectory tableDirectory;
     JDBCConnection conn;
     
    UserJPanel(JPanel workArea, MenuDirectory menuDirectory, TableDirectory tableDirectory, JDBCConnection conn) {
        initComponents();
        this.workArea = workArea;
        this.menuDirectory = menuDirectory;
        this.tableDirectory = tableDirectory;
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPOrder = new javax.swing.JButton();
        btnRTable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnPOrder.setText("Place Order");
        btnPOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPOrderActionPerformed(evt);
            }
        });

        btnRTable.setText("Reserve Table");
        btnRTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRTableActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRTable, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(96, 96, 96)
                .addComponent(btnPOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(btnRTable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPOrderActionPerformed
        // TODO add your handling code here:
        OrderJPanel op = new OrderJPanel(workArea, menuDirectory, conn);
        workArea.add("OrderJPanel", op);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnPOrderActionPerformed

    private void btnRTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRTableActionPerformed
        // TODO add your handling code here:
        ReservationJPanel op = new ReservationJPanel(workArea, 	tableDirectory, conn);
        workArea.add("ReservationJPanel", op);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnRTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPOrder;
    private javax.swing.JButton btnRTable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
